version: '3.8'
services:
    db:
      image: postgres:latest
      command: postgres -c 'max_connections=500'
      restart: always
      environment:
          POSTGRES_USER: ${user}
          POSTGRES_PASSWORD: ${password}
          POSTGRES_DB: ${DBName}
          PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
          - postgres-db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    bot:
        build: 
            context: .
        restart:
            on-failure
        environment:
            ADMIN: ${ADMIN}
            BOTTOKEN: ${BOTTOKEN}
            DATABASEURL: ${DATABASEURL}
            WEBHOOKURL: ${WEBHOOKURL}
            TZ: Europe/Moscow
            TYPESTART: 
        depends_on:
            - db
volumes:
    postgres-db-data:
        name: postgres-db-data
